#!/usr/bin/env python3
"""Generate the q2-hdstats conda environment file from the QIIME 2 distribution lockfile.

Two deliberate deviations from the upstream file, both documented in the emitted
header so nobody has to rediscover them:

1. EXCLUSIONS -- the official 2026.7 linux-64 file is internally unsatisfiable.
   It pins `zlib=1.3.2` and `sortmerna=2.0`, but every sortmerna 2.0 build in
   bioconda requires `zlib >=1.2.11,<1.3.0a0`. conda fails with:
       package deblur-1.1.1 requires sortmerna 2.0, but none of the providers
       can be installed
   deblur is an amplicon denoising plugin. Neither q2-gglasso, q2-classo, nor any
   chapter of the tutorial uses it (verified by grep), so dropping the
   deblur/q2-deblur/sortmerna trio costs us nothing and makes the file solvable.

2. EXTRAS -- bokeh, zarr, numcodecs, plotly and gglasso are not in the
   distribution. They are appended here rather than installed by a second
   `conda install`, because a separate transaction lets the solver drift the
   distribution's pinned numpy/pandas.

c-lasso is NOT added here: it has no conda-forge package and must go in by
`pip install --no-deps c-lasso==1.0.11` after the env exists.

Usage:
    python scripts/make_env_yml.py envs/rachis-qiime2-linux-64-conda.yml \
                                  envs/q2-slr-qiime2-2026.7.yml
"""

import sys

# Unsatisfiable trio -- see docstring.
EXCLUDE = {"deblur", "q2-deblur", "sortmerna"}

EXTRAS = [
    "gglasso=0.3.0",
    "bokeh>=3.4,<4",
    "zarr>=2.18.3,<3",
    "numcodecs>=0.13,<0.16",
    "plotly>=6,<7",
    "pip",
]

HEADER = """\
# GENERATED by scripts/make_env_yml.py -- do not edit by hand.
#
# Source: QIIME 2 2026.7 `qiime2` distribution (formerly `amplicon`), linux-64.
#
# Deviation 1 -- removed: deblur, q2-deblur, sortmerna.
#   The upstream file is internally unsatisfiable: it pins zlib=1.3.2 while every
#   sortmerna 2.0 build in bioconda requires zlib >=1.2.11,<1.3.0a0. deblur is
#   unused by q2-gglasso, q2-classo and the whole tutorial.
#
# Deviation 2 -- added: gglasso, bokeh, zarr, numcodecs, plotly.
#   Not shipped by the distribution. Appended here so they solve in the SAME
#   transaction as the pinned distribution packages; a second `conda install`
#   is what lets the solver drift numpy/pandas.
#
# c-lasso is installed afterwards by pip (no conda-forge package exists).
"""


def main(src: str, dst: str) -> None:
    dropped, kept = [], []
    for line in open(src).read().splitlines():
        stripped = line.strip()
        if stripped.startswith("- "):
            # dependency lines look like "- name=version"
            name = stripped[2:].split("=")[0].split(" ")[0].strip()
            if name in EXCLUDE:
                dropped.append(stripped[2:])
                continue
        kept.append(line)

    out = [HEADER.rstrip(), *kept, *[f"- {e}" for e in EXTRAS]]
    open(dst, "w").write("\n".join(out) + "\n")

    print(f"wrote {dst}")
    print(f"  dropped ({len(dropped)}): {', '.join(dropped) or 'none'}")
    print(f"  added   ({len(EXTRAS)}): {', '.join(EXTRAS)}")
    missing = EXCLUDE - {d.split('=')[0] for d in dropped}
    if missing:
        print(f"  WARNING: expected to drop but did not find: {sorted(missing)}")


if __name__ == "__main__":
    if len(sys.argv) != 3:
        sys.exit(__doc__)
    main(sys.argv[1], sys.argv[2])
